# you can read more about security in the related section of the documentation

jms_security_extra:
    secure_all_services: false
    expressions: true
  
  
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Bdtln\UserBundle\Entity\User: sha512
        

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        #ROLE_SUPER_ADMIN is the webmaster

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
            

        main:
            pattern:    ^/
            anonymous:  true
            provider:   main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path:    /%locale%/
                #Default_target_path is the default path where we are redirected after login
            logout:
                path:   fos_user_security_logout
                target: /%locale%/
            remember_me:
                key:    %secret%
                        #secret is a parameter present in parameters.yml

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        - { path: ^/(fr|en)/register, roles: ROLE_SUPER_ADMIN, requires_channel: http|https }
        #Only SUPER_ADMIN can add a member